name: Update RSS Feed

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Generate RSS
        run: npm start

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f feeds/feed.xml ]; then
            git add feeds/feed.xml
            git commit -m "Auto-update RSS feed [skip ci]" || echo "No changes to commit"
            git push
          else
            echo "⚠️ feeds/feed.xml not found. Skipping commit."
          fi
